### ISSUE TITLE
"set_repo" method looking in projects, not repos

### ISSUE THREAD

**Issue by Jamamel** [ashbaldry/vstsr#1]
After successfully logging in using vsts_account$new method as such:
```
library(vstsr)
xc <- vsts_account$new({username}, {password}, {domain}, {project})
```
I then set the project like this:
```
xc$set_project({projectname})
```
I then try to connect to a given repo within that project to extract all commits by doing:
```
xc$set_repo({reponame})
```
at which point I get the following error:
` Error in xc$set_repo({reponame}) :{reponame} not in available repositories. `
This is not true, as the repo IS in my given project and I can see it when querying `xc` after assigning the relevant project. 

I believe the issue is "set_repo" is pointing to projects rather than repos, as seen by its source code:
```
> xc$set_repo
function (repo) 
{
    if (is.null(private$repos)) {
        repo_df <- vsts_get_repos(private$domain, private$project, 
            private$auth_key, quiet = TRUE)
        private$repos <- repo_df$name
    }
    if (!repo %in% private$projects) 
        stop(repo, " not in available repositories.")
    private$repo <- repo
    invisible(TRUE)
}
```

**Comment by ashbaldry** [comment]
Fixed to look at repos instead of projects
